=== DavidVieiro/XSD/Ejemplo para explicar GRUPOS y comparar con content Contiene XML y XSD/ordenadores.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
		>
	<xs:element name="Lista">
		<xs:complexType> 
			<xs:sequence>
				<xs:element name="ordenadorProfesor" type="tipoOrdenadorP"/>
				<xs:element name="ordenadorAlumno" type="tipoOrdenadorA"  maxOccurs="unbounded"/>
				<xs:element name="ordenadorJefatura" type="tipoOrdenadorJ" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:group name="tipoIPnombre">
		<xs:sequence>
			<xs:element name="IP" type="xs:string"/>
			<xs:element name="nombre" type="xs:string"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tipoOrdenadorP"> 
		<xs:sequence>
			<xs:group ref="tipoIPnombre" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoOrdenadorA"> 
		<xs:sequence>
			<xs:group ref="tipoIPnombre" />
			<xs:element name="alumno" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoOrdenadorJ"> 
		<xs:sequence>
			<xs:group ref="tipoIPnombre" />
			<xs:element name="sala" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<!--
	<xs:complexType name="tipoOrdenadorP"> 
		<xs:sequence>
			<xs:element name="IP" type="xs:string"/>
			<xs:element name="nombre" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoOrdenadorA"> 
		<xs:complexContent>
			<xs:extension base="tipoOrdenadorP">
				<xs:sequence>
					<xs:element name="alumno" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="tipoOrdenadorJ"> 
		<xs:complexContent>
			<xs:extension base="tipoOrdenadorP">
				<xs:sequence>
					<xs:element name="sala" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="tipoOrdenadorA"> 
		<xs:sequence>
			<xs:element name="IP" type="xs:string"/>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="alumno" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoOrdenadorJ"> 
		<xs:sequence>
			<xs:element name="IP" type="xs:string"/>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="sala" type="xs:string"/>

		</xs:sequence>
	</xs:complexType>
	-->
</xs:schema>

=== DavidVieiro/XSD/Ejemplo para explicar GRUPOS y comparar con content Contiene XML y XSD/ordenadores.xml
<?xml version="1.0" encoding="utf-8"?>
<Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="ordenadores.xsd">
	<ordenadorProfesor>
		<IP>172.16.5.50</IP>
		<nombre>PC0500</nombre>
	</ordenadorProfesor>
	<ordenadorAlumno>
		<IP>172.16.5.50</IP>
		<nombre>PC0500</nombre>
		<alumno></alumno>
	</ordenadorAlumno>
	<ordenadorAlumno>
		<IP>172.16.5.50</IP>
		<nombre>PC0500</nombre>
		<alumno></alumno>
	</ordenadorAlumno>
	<ordenadorAlumno>
		<IP>172.16.5.50</IP>
		<nombre>PC0500</nombre>
		<alumno></alumno>
	</ordenadorAlumno>
	<ordenadorJefatura>
		<IP>172.16.5.50</IP>
		<nombre>PC0500</nombre>
		<sala></sala>
	</ordenadorJefatura>
	<ordenadorJefatura>
		<IP>172.16.5.50</IP>
		<nombre>PC0500</nombre>
		<sala></sala>
	</ordenadorJefatura>
</Lista>

<!-- Para explicar grupos de atributos aÃ±adimos mac, sistema operativo y ram como atributos a ordenadorJefatura
 mac y sistema operativo a ordenadorAlumno -->
