=== DavidVieiro/XSD/simpleContent y complexContent Persona/personas.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd">
	
	<xs:element name="agenda">
		<xs:complexType> 
			<xs:sequence>
				<xs:element name="persona1" type="tipoPersona1" />
				<xs:element name="persona2" type="tipoPersona2" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="tipoPersona1"> 
		<xs:sequence>
			<xs:group ref="tipoNombreApellidos" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoPersona2"> 
		<xs:sequence>
			<xs:group ref="tipoNombreApellidos" />
			<xs:element name="direccion" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="edad" type="xs:positiveInteger" />
	</xs:complexType>
	
	<xs:group name="tipoNombreApellidos">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string" />
			<xs:element name="apellido" type="xs:string" />
		</xs:sequence>
	</xs:group>
	
</xs:schema>

=== DavidVieiro/XSD/simpleContent y complexContent Persona/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personas.xsd">   
      <persona1>
        <nombre>pepe</nombre>
        <apellido>Lopez</apellido>        
      </persona1> 
           
      <persona2 edad="20">
        <nombre>pepe</nombre>
        <apellido>Lopez</apellido>
        <direccion>C/Mayor</direccion>
      </persona2> 
</agenda>

<!--
Tenemos un tipo de datos: datospersonales1 que contiene los elementos: nombre y apellido. Creamos datospersonales2 a partir del anterior aÃ±adinedole el elemento direccion y el atributo edad.
-->
