=== DavidVieiro/XSD/CLAVES (Ordenadores)/ordenadores.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd">
	<xs:element name="Lista">
		<xs:complexType>
			<xs:sequence>
			
				<!--Ordenador Profesor-->
				<xs:element name="ordenadorProfesor" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>							
							<xs:element name="IP" type="xs:string"/>
							<xs:element name="nombre" type="xs:string"/>							
						</xs:sequence>
						<!--Los atributos siempre entre secuence y complexType-->
						<xs:attribute name="mac" type="xs:string"/>
						<xs:attribute name="aula" type="xs:string"/>
						<xs:attribute name="so" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="ordenadorAlumno" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="IP" type="xs:string"/>							
							<xs:element name="nombre" type="xs:string"/>								
							<xs:element name="alumno" type="xs:string"/>
						</xs:sequence>						
						<xs:attribute name="mac" type="xs:string"/>
						<xs:attribute name="aula" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="ordenadorJefatura" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="IP" type="xs:string"/>								
							<xs:element name="nombre" type="xs:string"/>								
							<xs:element name="sala" type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="sala" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="numero" type="xs:integer"/>								
							<xs:element name="ubicacion" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		
		<!--clave-->
		<xs:key name="PK_ordenadorAlumno">
			<xs:selector xpath="ordenadorAlumno"/>
			<xs:field xpath="IP"/>
		</xs:key>
		
		<xs:key name="PK_ordenadorProfesor">
			<xs:selector xpath="ordenadorProfesor"/>
			<xs:field xpath="@mac"/>
		</xs:key>
		
		<xs:key name="PK_sala">
			<xs:selector xpath="sala"/>
			<xs:field xpath="numero"/>
		</xs:key>
		
		<xs:keyref name="FK_sala" refer="PK_sala">
			<xs:selector xpath="ordenadorJefatura"/>
			<xs:field xpath="sala"/>
		</xs:keyref>
		
	</xs:element>
</xs:schema>

=== DavidVieiro/XSD/CLAVES (Ordenadores)/ordenadores.xml
<?xml version="1.0" encoding="utf-8"?>
 <Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="ordenadores.xsd">
	<ordenadorProfesor mac="11:11:22:88:AA:11" aula="B05" so="Windows7">
		<IP>172172.16.5.60</IP>
		<nombre>PC0500</nombre>
	</ordenadorProfesor>
	<ordenadorProfesor mac="12:11:22:88:AA:11" aula="B05" so="Windows7">
		<IP>172172.16.5.60</IP>
		<nombre>PC0500</nombre>
	</ordenadorProfesor>
	<ordenadorAlumno mac="11:11:22:88:AA:11" aula="B05">
		<IP>172.16.5.50</IP>
		<nombre>PC0500</nombre>		
		<alumno>Pepe</alumno>		
	</ordenadorAlumno>
	<ordenadorAlumno mac="11:11:22:88:AA:11" aula="B05">
		<IP>172.16.5.51</IP>
		<nombre>PC0500</nombre>		
		<alumno>Pepe</alumno>		
	</ordenadorAlumno>
	<ordenadorAlumno mac="11:11:22:88:AA:11" aula="B05">
		<IP>172.16.5.52</IP>
		<nombre>PC0500</nombre>		
		<alumno>Pepe</alumno>		
	</ordenadorAlumno>	
	<ordenadorJefatura>
		<IP>172.16.5.70</IP>
		<nombre>PC0500</nombre>
		<sala>11</sala>
	</ordenadorJefatura>
	<ordenadorJefatura>
		<IP>172.16.5.80</IP>
		<nombre>PC0500</nombre>
		<sala>12</sala>
	</ordenadorJefatura>
	<sala>
		<numero>11</numero>
		<ubicacion>Planta 1</ubicacion>
	</sala>
	<sala>
		<numero>12</numero>
		<ubicacion>Planta 1</ubicacion>
	</sala>
 </Lista>
 <!-- -->
 <!--Clave principal: IP de ordenador de alumno-->
 <!--Clave principal: mac del ordenador de profesor-->
 <!--sala clave ajena -->
