=== DavidVieiro/XSD/Ejercicio Base CURSO 6 [Content]/curso.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
		>
	<xs:element name="Lista">
		<xs:complexType> <!-- lista es complejo porque contiene elementos -->
			<xs:sequence>
				<xs:element name="Curso" maxOccurs="unbounded">
					<xs:complexType>  <!-- curso es complejo porque contiene elementos -->
						<xs:sequence>
							<xs:element name="Titulo" type="xs:string"/>
							<xs:element name="Horas" type="xs:nonNegativeInteger"/>
							<xs:element name="alumno" type="tipoAlumno"/>
							<xs:element name="profesor" type="tipoProfesor"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="tipoAlumno">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string" />
			<xs:element name="apellidos" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoProfesor">
		<xs:complexContent>
			<xs:extension base="tipoAlumno">
				<xs:sequence>
					<xs:element name="modulo" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	

</xs:schema>

=== DavidVieiro/XSD/Ejercicio Base CURSO 6 [Content]/1curso.xml
<?xml version="1.0" encoding="utf-8"?>
 <Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="curso.xsd">
	<Curso>
		<Titulo>Lenguaje de Marcas</Titulo>
		<Horas>200</Horas>
		<alumno>
			<nombre>Pepe</nombre>
			<apellidos>Perez</apellidos>
		</alumno>
		<profesor>
			<nombre>Ana</nombre>
			<apellidos>Lopez</apellidos>
			<modulo>LM</modulo>
		</profesor>
		<bedel>
			<nombre>Jose</nombre>
			<apellidos>Gomez</apellidos>
			<turno>Ma√±anas</turno>
		</bedel>
		<director antiguedad="4">
			<nombre>Jose</nombre>
			<apellidos>Gomez</apellidos>
		</director>
	</Curso>
	<Curso>
		<Titulo>BBDD</Titulo>
		<Horas>210</Horas>
		<alumno>
			<nombre>Pepe</nombre>
			<apellidos>Perez</apellidos>
		</alumno>
		<profesor>
			<nombre>Ana</nombre>
			<apellidos>Lopez</apellidos>
			<modulo>LM</modulo>
		</profesor>
	</Curso>
 </Lista>
