=== DavidVieiro/XSD/Ejercicio Base CURSO 2/curso.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
>
    <xs:element name="Lista">
       <xs:complexType> <!-- lista es complejo porque contiene elementos -->
           <xs:sequence>
             <xs:element name="Curso" maxOccurs="unbounded">
               <xs:complexType>  <!-- curso es complejo porque contiene elementos -->
                 <xs:sequence>
                       <xs:element name="Titulo" type="xs:string" />
                       <xs:element name="tituloCorto" type="tituloTC" />
                       <xs:element name="grupo" type="tipoGrupo" minOccurs="0" />
					   <xs:element name="nocturno" type="xs:boolean" />
                       <xs:element name="Horas" type="xs:nonNegativeInteger" minOccurs="0" />
                       <xs:element name="fechaComienzo" type="xs:date" />
                       <xs:element name="horaComienzo" type="xs:time" />
                       <xs:element name="precio" type="xs:float" maxOccurs="unbounded" />
                       <xs:element name="tema" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                       <xs:element name="telefono" type="telefono1"/>
					   <xs:element name="telefonoMovil" type="telefono2" />
                 </xs:sequence>
              </xs:complexType>
             </xs:element>
           </xs:sequence>
       </xs:complexType>
    </xs:element>
	<!-- TIPOS DE DATOS -->
	<xs:simpleType name="tituloTC">
		<xs:restriction base="xs:string">
			<xs:minLength value="2" />
			<xs:maxLength value="4" />
		</xs:restriction>
    </xs:simpleType>
	
	<xs:simpleType name="tipoGrupo">
		<xs:restriction base="xs:string">
			<xs:pattern value="ASI[1-8]" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="telefono1">
		<xs:restriction base="xs:string">
			<xs:pattern value="[98]81-[0-9]{6}" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="telefono2">
		<xs:restriction base="xs:string">
			<xs:pattern value="[67]\d{2}\s\d{2}\s\d{2}\s\d{2}" />
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>


<!--  Estructura:
    Lista: es una secuencia de un solo elemento:curso
         Curso : es una secuencia de dos elementos:titulo y horas. El curso se repite.
              Titulo
              Horas
         Curso
              TÃ­tulo
              Horas
 -->

=== DavidVieiro/XSD/Ejercicio Base CURSO/1curso.xml
<?xml version="1.0" encoding="utf-8"?>
 <Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="curso.xsd">
	<Curso>
		<Titulo>Lenguaje de Marcas</Titulo>
		<nocturno>false</nocturno>
		<Horas>200</Horas>
		<fechaComienzo>2017-03-17</fechaComienzo>
	</Curso>
	<Curso>
		<Titulo>BBDD</Titulo>
		<nocturno>true</nocturno>
		<Horas>210</Horas>
		<fechaComienzo>2017-03-20</fechaComienzo>
	</Curso>
 </Lista>

=== DavidVieiro/XSD/Ejercicio Base CURSO 2/1curso.xml
<?xml version="1.0" encoding="utf-8"?>
 <Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="curso.xsd">
	<Curso>
		<Titulo>Lenguaje de Marcas</Titulo>
		<tituloCorto>LM</tituloCorto>
		<nocturno>false</nocturno>
		<Horas>200</Horas>
		<fechaComienzo>2017-03-17</fechaComienzo>
		<horaComienzo>08:30:00</horaComienzo>
		<precio>20.0</precio>
		<precio>30.0</precio>
		<precio>40.0</precio>
		<tema>Introduccion</tema>
		<tema>Desarrollo</tema>
		<telefono>981619900</telefono>
		<telefono>981619800</telefono>
	</Curso>
	<Curso>
		<Titulo>Bases de Datos</Titulo>
		<tituloCorto>BBDD</tituloCorto>
		<nocturno>true</nocturno>
		<Horas>210</Horas>
		<fechaComienzo>2017-03-20</fechaComienzo>
		<horaComienzo>09:30:00</horaComienzo>
		<precio>20.0</precio>
		<telefono>981619900</telefono>
		<telefono>981619800</telefono>
	</Curso>
 </Lista>
